# Generated by Django 2.1.5 on 2021-12-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dat_posted',
            new_name='date_posted',
        ),
    ]
